### ISSUE TITLE
unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by SebLKMa** [sgloutnikov/gqlgen-react-chatapp#1]
`
$ yarn
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/ScriptedAlchemy/html-webpack-plugin
Directory: /home/ubuntu/go/src/code.in.spdigital.sg/sebastianmlk/azure-blob-pd-ntu/gqlgen-react-chatapp/client
Output:
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

In `package.json`, I think we have to 
replace 
`"html-webpack-plugin": "git://github.com/ScriptedAlchemy/html-webpack-plugin#master",`
with
`"html-webpack-plugin": "https://github.com/ScriptedAlchemy/html-webpack-plugin#master",`

**Comment by sgloutnikov** [comment]
Thanks for pointing this out! Just pushed a version bump and changed this one. Back to normal on my end when I tested.
